package studio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/zionrubin/loom/core"
	"github.com/zionrubin/loom/model"
)

// Go renders the document as a Go program.
//
// The export is not a picture of the pipeline in another notation — it is the
// same pipeline, built through the same authoring API, and it compiles. That
// is the property worth insisting on: a studio you cannot leave is a trap, and
// the way out of this one is a file you can drop into a repository, put under
// review, and edit by hand from then on.
//
// Two things in the generated program are library calls rather than generated
// code, because they are library code in the studio too: a source reads
// through [LoadRecords] with the spec the canvas holds, and a derived field
// renders through the same text/template with the same [TemplateFuncs]. A
// filter compiles to the Go you would have written, except for the ordered
// comparisons, which route through [Cond.Match] so that the exported program
// compares numbers the way the studio does rather than the way a naive
// string comparison would.
//
// Editing the canvas regenerates this file. It is an export, not a second
// source of truth.
func (d *Doc) Go() (string, error) {
	if err := d.Validate(); err != nil {
		return "", err
	}
	order, err := d.Order()
	if err != nil {
		return "", err
	}
	g := &gen{
		imports: map[string]bool{},
		names:   map[string]string{},
		taken:   map[string]bool{},
	}
	g.use("github.com/zionrubin/loom/pipeline")
	g.use("github.com/zionrubin/loom/core")

	second := d.SecondPass()
	var body bytes.Buffer
	g.out = &body
	g.p("// build assembles %s. Every step on the canvas is one call here.", strconv.Quote(d.Name))
	g.p("func build() (*pipeline.Pipeline, error) {")
	g.p("\tp := pipeline.New(%s)", lit(d.Name))
	for _, s := range order {
		if second[s.ID] {
			continue
		}
		g.p("")
		if err := g.step(d, s, "p"); err != nil {
			return "", err
		}
	}
	g.p("")
	g.p("\treturn p, nil")
	g.p("}")

	if len(d.Merges()) > 0 {
		g.p("")
		g.p("// buildSecond assembles the second pass: a fold over what the first")
		g.p("// run produced, and whatever reads it. Branches fan out but never fan")
		g.p("// back in, so a step that reads several of them is another run rather")
		g.p("// than another stage.")
		g.p("func buildSecond(out map[string][]core.Record) (*pipeline.Pipeline, error) {")
		g.p("\tp := pipeline.New(%s)", lit(d.SecondName()))
		for _, s := range order {
			if !second[s.ID] {
				continue
			}
			g.p("")
			if !s.Merging() {
				if err := g.step(d, s, "p"); err != nil {
					return "", err
				}
				continue
			}
			in := g.name(s.ID) + "In"
			g.p("\tvar %s []core.Record", in)
			for _, up := range s.Merge {
				g.p("\t%s = append(%s, out[%s]...)", in, in, lit(up))
			}
			g.p("\tif len(%s) == 0 {", in)
			g.p("\t\treturn nil, fmt.Errorf(%s)", lit("nothing to fold into "+s.ID))
			g.p("\t}")
			g.use("fmt")
			g.p("\t// %s", describe(s))
			src := fmt.Sprintf("p.FromRecords(%s, %s)", lit(s.ID+"-in"), in)
			if err := g.reduce(s, src, len(d.Children(s.ID)) > 0); err != nil {
				return "", err
			}
		}
		g.p("")
		g.p("\treturn p, nil")
		g.p("}")
	}

	g.main(d)

	var head bytes.Buffer
	fmt.Fprintf(&head, "// Code generated by Loom Studio from %s. DO NOT EDIT — or do:\n"+
		"// this is the pipeline itself, not a description of one, and once it is\n"+
		"// in a repository it is yours.\n\npackage main\n\n", strconv.Quote(d.Name))
	head.WriteString(g.importBlock())
	if g.helpers.Len() > 0 {
		head.WriteString("\n")
		head.Write(g.helpers.Bytes())
	}
	head.WriteString("\n")
	head.Write(body.Bytes())

	src, err := format.Source(head.Bytes())
	if err != nil {
		// A generator that emits invalid Go should say so loudly rather than
		// hand back something that looks like code.
		return head.String(), fmt.Errorf("studio: generated Go does not parse: %w", err)
	}
	return string(src), nil
}

// gen accumulates a generated program: the body, the helpers hoisted to
// package scope, and the import set the two of them earned.
type gen struct {
	out     *bytes.Buffer
	helpers bytes.Buffer
	imports map[string]bool
	names   map[string]string
	taken   map[string]bool
}

func (g *gen) p(format string, args ...any) {
	fmt.Fprintf(g.out, format+"\n", args...)
}

func (g *gen) use(path string) { g.imports[path] = true }

func (g *gen) importBlock() string {
	var std, own []string
	for p := range g.imports {
		if strings.HasPrefix(p, "github.com/zionrubin/loom") {
			own = append(own, p)
			continue
		}
		std = append(std, p)
	}
	sort.Strings(std)
	sort.Strings(own)
	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	if len(own) > 0 && len(std) > 0 {
		b.WriteString("\n")
	}
	for _, p := range own {
		if p == "github.com/zionrubin/loom" {
			fmt.Fprintf(&b, "\tloom %q\n", p)
			continue
		}
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	b.WriteString(")\n")
	return b.String()
}

// name is the Go variable for a step, memoized so the same step is always the
// same identifier.
func (g *gen) name(id string) string {
	if n, ok := g.names[id]; ok {
		return n
	}
	n := camel(id)
	if goKeyword[n] || g.taken[n] {
		n += "Step"
	}
	for i := 2; g.taken[n]; i++ {
		n = camel(id) + strconv.Itoa(i)
	}
	g.taken[n] = true
	g.names[id] = n
	return n
}

// step emits one step of the first pass.
func (g *gen) step(d *Doc, s *Step, root string) error {
	if s.Kind == KindSource {
		g.use("context")
		g.p("\t// %s", describe(s))
		g.p("\t%s := %s.FromFunc(%s, func(ctx context.Context) ([]core.Record, error) {",
			g.name(s.ID), root, lit(s.ID))
		g.use("github.com/zionrubin/loom/studio")
		g.p("\t\treturn studio.LoadRecords(ctx, &studio.SourceSpec{")
		g.sourceFields(s.Source)
		g.p("\t\t})")
		g.p("\t})")
		return nil
	}
	up := g.name(s.From)
	assigned := len(d.Children(s.ID)) > 0
	g.p("\t// %s", describe(s))
	switch s.Kind {
	case KindInfer:
		return g.infer(s, up, assigned)
	case KindReduce:
		return g.reduce(s, up, assigned)
	case KindLoop:
		return g.loop(s, up, assigned)
	case KindFilter:
		return g.filter(s, up, assigned)
	case KindDerive:
		return g.derive(s, up, assigned)
	case KindWrite:
		return g.write(s, up, assigned)
	}
	return fmt.Errorf("studio: cannot export step %q of kind %q", s.ID, s.Kind)
}

func (g *gen) lhs(s *Step, assigned bool) string {
	if assigned {
		return "\t" + g.name(s.ID) + " := "
	}
	return "\t"
}

func (g *gen) sourceFields(sp *SourceSpec) {
	g.p("\t\t\tFrom: %s,", lit(sp.From))
	if sp.Root != "" {
		g.p("\t\t\tRoot: %s,", lit(sp.Root))
	}
	if sp.Path != "" {
		g.p("\t\t\tPath: %s,", lit(sp.Path))
	}
	if sp.Match != "" {
		g.p("\t\t\tMatch: %s,", lit(sp.Match))
	}
	if sp.Since != "" {
		g.p("\t\t\tSince: %s,", lit(sp.Since))
	}
	if sp.Until != "" {
		g.p("\t\t\tUntil: %s,", lit(sp.Until))
	}
	if sp.Line != "" {
		g.p("\t\t\tLine: %s,", lit(sp.Line))
	}
	if sp.Limit > 0 {
		g.p("\t\t\tLimit: %d,", sp.Limit)
	}
	if len(sp.Scrub) > 0 {
		g.p("\t\t\tScrub: %s,", strSlice(sp.Scrub))
	}
	if len(sp.Fields) > 0 {
		keys := make([]string, 0, len(sp.Fields))
		for k := range sp.Fields {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		g.p("\t\t\tFields: map[string]string{")
		for _, k := range keys {
			g.p("\t\t\t\t%s: %s,", lit(k), lit(sp.Fields[k]))
		}
		g.p("\t\t\t},")
	}
	if len(sp.Records) > 0 {
		g.use("encoding/json")
		blob, err := marshalRecords(sp.Records)
		if err != nil {
			blob = "[]"
		}
		g.p("\t\t\tRecords: mustRecords(%s),", lit(blob))
		g.recordsHelper()
	}
}

// recordsHelper emits the one helper an inline-records source needs, once.
func (g *gen) recordsHelper() {
	if g.taken["mustRecords"] {
		return
	}
	g.taken["mustRecords"] = true
	g.helpers.WriteString(`
// mustRecords decodes the records the document carries inline.
func mustRecords(blob string) []core.Record {
	var recs []core.Record
	if err := json.Unmarshal([]byte(blob), &recs); err != nil {
		panic(err)
	}
	return recs
}
`)
}

func (g *gen) infer(s *Step, up string, assigned bool) error {
	spec, err := s.Infer.compile(s.ID)
	if err != nil {
		return err
	}
	g.p("%s%s.Infer(%s, pipeline.InferSpec{", g.lhs(s, assigned), up, lit(s.ID))
	g.inferBody(s.Infer, spec.Prompt, "\t\t")
	if s.Infer.Workers > 0 {
		g.p("\t}, pipeline.WithParallelism(%d))", s.Infer.Workers)
		return nil
	}
	g.p("\t})")
	return nil
}

// inferBody emits the shared fields of an InferSpec literal, at the given
// indent, so a loop's step and a plain inference read the same way.
func (g *gen) inferBody(in *InferSpec, prompt, ind string) {
	g.use("github.com/zionrubin/loom/model")
	g.p("%sBinding: %s,", ind, bindingLit(in.Tier, in.Model, in.Escalate))
	if in.System != "" {
		g.p("%sSystem: %s,", ind, lit(in.System))
	}
	g.p("%sPrompt: %s,", ind, lit(prompt))
	if in.MaxTokens > 0 {
		g.p("%sMaxTokens: %d,", ind, in.MaxTokens)
	}
	if len(in.Answer) > 0 {
		g.p("%sParseJSON: true,", ind)
	} else if in.Output != "" {
		g.p("%sOutputField: %s,", ind, lit(in.Output))
	}
	req := in.required()
	if len(req) == 0 {
		return
	}
	g.use("fmt")
	g.p("%sValidate: func(r core.Record) error {", ind)
	for _, a := range req {
		if a.Kind == "list" {
			g.p("%s\tif l, _ := r.Data[%s].([]any); len(l) == 0 {", ind, lit(a.Name))
			g.p("%s\t\treturn fmt.Errorf(%s)", ind, lit("empty "+a.Name))
			g.p("%s\t}", ind)
			continue
		}
		g.use("strings")
		g.p("%s\tif strings.TrimSpace(r.String(%s)) == \"\" {", ind, lit(a.Name))
		g.p("%s\t\treturn fmt.Errorf(%s)", ind, lit("empty "+a.Name))
		g.p("%s\t}", ind)
	}
	g.p("%s\treturn nil", ind)
	g.p("%s},", ind)
}

func (g *gen) reduce(s *Step, up string, assigned bool) error {
	r := s.Reduce
	g.use("github.com/zionrubin/loom/model")
	g.p("%s%s.ReduceAI(%s, pipeline.ReduceAISpec{", g.lhs(s, assigned), up, lit(s.ID))
	g.p("\t\tBinding: %s,", bindingLit(r.Tier, r.Model, nil))
	if r.System != "" {
		g.p("\t\tSystem: %s,", lit(r.System))
	}
	g.p("\t\tPrompt: %s,", lit(r.prompt()))
	if r.FanIn > 0 {
		g.p("\t\tFanIn: %d,", r.FanIn)
	}
	if r.MaxTokens > 0 {
		g.p("\t\tMaxTokens: %d,", r.MaxTokens)
	}
	if r.ItemField != "" {
		g.p("\t\tItemField: %s,", lit(r.ItemField))
	}
	if r.Output != "" {
		g.p("\t\tOutputField: %s,", lit(r.Output))
	}
	g.p("\t})")
	return nil
}

func (g *gen) loop(s *Step, up string, assigned bool) error {
	spec, err := s.Loop.Step.compile(s.ID)
	if err != nil {
		return err
	}
	g.use("github.com/zionrubin/loom/algo")
	name := g.name(s.ID) + "Refine"
	g.p("\t%s, err := algo.NewRefine(algo.RefineConfig{", name)
	g.p("\t\tAccept: func(r core.Record) bool { ok, _ := %s.Match(r); return ok },", condLit(s.Loop.Until))
	g.use("github.com/zionrubin/loom/studio")
	g.p("\t\tNote: func(r core.Record) string { return r.String(%s) },", lit(field(s.Loop.Note, "critique")))
	if s.Loop.Carry {
		g.p("\t\tCarry: true,")
	}
	g.p("\t})")
	g.p("\tif err != nil {")
	g.p("\t\treturn nil, err")
	g.p("\t}")
	g.p("%s%s.Iterate(%s, pipeline.IterateSpec{", g.lhs(s, assigned), up, lit(s.ID))
	g.p("\t\tStep: pipeline.InferSpec{")
	g.inferBody(&s.Loop.Step, spec.Prompt, "\t\t\t")
	g.p("\t\t},")
	g.p("\t\tAlgorithm: %s,", name)
	g.p("\t\tHalt: pipeline.HaltWhen{")
	g.p("\t\t\tMaxRounds: %d,", s.Loop.Rounds)
	if s.Loop.CapUSD > 0 {
		g.p("\t\t\tBudget: core.Budget{MaxCostUSD: %s},", num(s.Loop.CapUSD))
	}
	g.p("\t\t},")
	g.p("\t})")
	return nil
}

func (g *gen) filter(s *Step, up string, assigned bool) error {
	c := *s.Keep
	g.p("%s%s.Filter(%s, func(r core.Record) (bool, error) {", g.lhs(s, assigned), up, lit(s.ID))
	switch c.Op {
	case "is":
		g.p("\t\treturn r.String(%s) == %s, nil", lit(c.Field), lit(c.Value))
	case "is-not":
		g.p("\t\treturn r.String(%s) != %s, nil", lit(c.Field), lit(c.Value))
	case "contains":
		g.use("strings")
		g.p("\t\treturn strings.Contains(r.String(%s), %s), nil", lit(c.Field), lit(c.Value))
	case "not-contains":
		g.use("strings")
		g.p("\t\treturn !strings.Contains(r.String(%s), %s), nil", lit(c.Field), lit(c.Value))
	case "non-empty":
		g.use("strings")
		g.p("\t\treturn strings.TrimSpace(r.String(%s)) != \"\", nil", lit(c.Field))
	case "empty":
		g.use("strings")
		g.p("\t\treturn strings.TrimSpace(r.String(%s)) == \"\", nil", lit(c.Field))
	case "exists":
		g.p("\t\t_, ok := r.Data[%s]", lit(c.Field))
		g.p("\t\treturn ok, nil")
	case "missing":
		g.p("\t\t_, ok := r.Data[%s]", lit(c.Field))
		g.p("\t\treturn !ok, nil")
	default:
		// Ordered comparisons compare as numbers when both sides are numbers
		// and lexically when they are not, which is one line of library rather
		// than eight of generated code that could drift from it.
		g.use("github.com/zionrubin/loom/studio")
		g.p("\t\treturn %s.Match(r)", condLit(c))
	}
	g.p("\t}, pipeline.WithVersion(%s))", lit(versionOf("keep", c.Field, c.Op, c.Value)))
	return nil
}

func (g *gen) derive(s *Step, up string, assigned bool) error {
	f := *s.Field
	if _, err := parseTemplate(s.ID, f.Template); err != nil {
		return err
	}
	fn := g.name(s.ID) + "Field"
	tpl := g.name(s.ID) + "Template"
	g.use("text/template")
	g.use("strings")
	g.use("github.com/zionrubin/loom/studio")
	fmt.Fprintf(&g.helpers, `
// %s renders the %s field of every record passing through %q.
var %s = template.Must(template.New(%s).
	Funcs(studio.TemplateFuncs()).Option("missingkey=zero").
	Parse(%s))

func %s(r core.Record) (core.Record, error) {
	var sb strings.Builder
	if err := %s.Execute(&sb, r.Data); err != nil {
		return core.Record{}, core.Permanent(err)
	}
	out := r.Clone()
	out.Data[%s] = sb.String()
	return out, nil
}
`, tpl, f.Name, s.ID, tpl, lit(s.ID), lit(f.Template), fn, tpl, lit(f.Name))
	// The version is the hash of the template: change what the field says and
	// the cached records that carried the old value stop matching.
	g.p("%s%s.Map(%s, %s, pipeline.WithVersion(%s))",
		g.lhs(s, assigned), up, lit(s.ID), fn, lit(versionOf("field", f.Name, f.Template)))
	return nil
}

func (g *gen) write(s *Step, up string, assigned bool) error {
	w := *s.Write
	body := field(w.Body, "{{.output}}")
	if _, err := parseTemplate(s.ID+".name", w.Name); err != nil {
		return err
	}
	if _, err := parseTemplate(s.ID+".body", body); err != nil {
		return err
	}
	fn := g.name(s.ID) + "File"
	g.use("text/template")
	g.use("strings")
	g.use("os")
	g.use("path/filepath")
	g.use("github.com/zionrubin/loom/studio")
	fmt.Fprintf(&g.helpers, `
// %s writes one record to %s and records the path it wrote.
var (
	%sName = template.Must(template.New(%s).
		Funcs(studio.TemplateFuncs()).Option("missingkey=zero").Parse(%s))
	%sBody = template.Must(template.New(%s).
		Funcs(studio.TemplateFuncs()).Option("missingkey=zero").Parse(%s))
)

func %s(r core.Record) (core.Record, error) {
	var name, body strings.Builder
	if err := %sName.Execute(&name, r.Data); err != nil {
		return core.Record{}, core.Permanent(err)
	}
	if err := %sBody.Execute(&body, r.Data); err != nil {
		return core.Record{}, core.Permanent(err)
	}
	if err := os.MkdirAll(%s, 0o755); err != nil {
		return core.Record{}, err
	}
	path := filepath.Join(%s, filepath.Base(name.String()))
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return core.Record{}, err
	}
	out := r.Clone()
	out.Data["path"] = path
	return out, nil
}
`, fn, w.Dir,
		fn, lit(s.ID+".name"), lit(w.Name),
		fn, lit(s.ID+".body"), lit(body),
		fn, fn, fn, lit(w.Dir), lit(w.Dir))
	// Never cached: a replayed write is a file that silently did not get
	// written.
	g.p("%s%s.Map(%s, %s, pipeline.WithNoCache())", g.lhs(s, assigned), up, lit(s.ID), fn)
	return nil
}

// main emits the program's entry point: register models, run, report.
func (g *gen) main(d *Doc) {
	g.use("context")
	g.use("fmt")
	g.use("log")
	g.use("github.com/zionrubin/loom")
	g.use("github.com/zionrubin/loom/model")
	g.p("")
	g.p("func main() {")
	g.p("\t// Register the models the steps above bind to, e.g.")
	g.p("\t//   openai.RegisterDefaults(reg, model.Limits{RequestsPerMinute: 200})")
	g.p("\t// and hand the run its key with loom.WithSecrets.")
	g.p("\treg := model.NewRegistry()")
	g.p("")
	g.p("\tp, err := build()")
	g.p("\tif err != nil {")
	g.p("\t\tlog.Fatal(err)")
	g.p("\t}")
	g.p("\topts := []loom.Option{")
	g.p("\t\tloom.WithRegistry(reg),")
	if d.CapUSD > 0 {
		g.p("\t\tloom.WithRunBudget(core.Budget{MaxCostUSD: %s}),", num(d.CapUSD))
	}
	if d.Workers > 0 {
		g.p("\t\tloom.WithWorkers(%d),", d.Workers)
	}
	if d.KeepGoing {
		g.p("\t\tloom.WithContinueOnError(),")
	}
	g.p("\t\tloom.WithStateDir(\"./state\"), // cache = checkpoint = resume")
	g.p("\t}")
	g.p("\tres, err := loom.Run(context.Background(), p, opts...)")
	g.p("\tif err != nil && res == nil {")
	g.p("\t\tlog.Fatal(err)")
	g.p("\t}")
	g.p("\tfmt.Print(res.Report)")
	if len(d.Merges()) > 0 {
		g.p("")
		g.p("\tsecond, err := buildSecond(res.StageOutputs)")
		g.p("\tif err != nil {")
		g.p("\t\tlog.Fatal(err)")
		g.p("\t}")
		g.p("\tres2, err := loom.Run(context.Background(), second, opts...)")
		g.p("\tif err != nil && res2 == nil {")
		g.p("\t\tlog.Fatal(err)")
		g.p("\t}")
		g.p("\tfmt.Print(res2.Report)")
	}
	g.p("}")
}

// --- literals --------------------------------------------------------------

// lit renders a Go string literal, preferring a raw literal for anything with
// a newline in it because a prompt is meant to be read.
func lit(s string) string {
	if strings.Contains(s, "\n") && !strings.Contains(s, "`") && !strings.Contains(s, "\r") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

func num(f float64) string { return strconv.FormatFloat(f, 'g', -1, 64) }

func strSlice(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = lit(s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func bindingLit(tier, id string, escalate []string) string {
	b := binding(tier, id, escalate)
	var parts []string
	if b.Model != "" {
		parts = append(parts, "Model: "+lit(b.Model))
	}
	if b.Tier != "" {
		parts = append(parts, "Tier: model."+tierConst(b.Tier))
	}
	if len(b.Escalation) > 0 {
		parts = append(parts, "Escalation: "+strSlice(b.Escalation))
	}
	return "model.Binding{" + strings.Join(parts, ", ") + "}"
}

func tierConst(t model.Tier) string {
	switch t {
	case model.TierFast:
		return "TierFast"
	case model.TierBalanced:
		return "TierBalanced"
	case model.TierDeep:
		return "TierDeep"
	}
	return "Tier(" + strconv.Quote(string(t)) + ")"
}

func condLit(c Cond) string {
	return fmt.Sprintf("(studio.Cond{Field: %s, Op: %s, Value: %s})",
		lit(c.Field), lit(c.Op), lit(c.Value))
}

// marshalRecords renders inline records as the JSON blob the exported program
// decodes at startup: a document that carries its own input keeps carrying it.
func marshalRecords(recs []core.Record) (string, error) {
	b, err := json.MarshalIndent(recs, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// describe is the one-line comment above a generated step: what the card on
// the canvas says, so the file reads like the picture.
func describe(s *Step) string {
	title := field(s.Title, s.ID)
	switch s.Kind {
	case KindSource:
		return title + " — records in"
	case KindInfer:
		return title + " — one model call per record"
	case KindReduce:
		if s.Merging() {
			return title + " — folds " + strings.Join(s.Merge, ", ")
		}
		return title + " — folds every record into one"
	case KindLoop:
		return title + " — repeats until " + s.Loop.Until.String()
	case KindFilter:
		return title + " — keeps records where " + s.Keep.String()
	case KindDerive:
		return title + " — adds " + s.Field.Name + ", no model"
	case KindWrite:
		return title + " — writes " + s.Write.Name + " into " + s.Write.Dir
	}
	return title
}

func camel(id string) string {
	parts := strings.FieldsFunc(id, func(r rune) bool { return r == '-' || r == '_' || r == '.' })
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		if i == 0 {
			b.WriteRune(unicode.ToLower(r[0]))
		} else {
			b.WriteRune(unicode.ToUpper(r[0]))
		}
		b.WriteString(string(r[1:]))
	}
	if b.Len() == 0 {
		return "step"
	}
	return b.String()
}

var goKeyword = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
	"len": true, "cap": true, "new": true, "make": true, "err": true, "p": true,
}
